name: Unit tests

on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test
